language: bash
services: docker
before_install: 
  - echo "We are in the docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push leobuck/mysql-rest-with-spring-boot-udemy;
    docker push leobuck/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false